### ISSUE TITLE
CodingCoach Programming w/Style

### ISSUE THREAD

**Issue by CMoskey** [briangormanly/agora#1]
Safari Version 15.1 (17612.3.5)

Some buttons no popping up in color (Enroll, Continue, Etc) 
<img width="102" alt="Next Step" src="https://user-images.githubusercontent.com/70187908/150567474-f0bbe867-50ef-482a-87a9-b1b8821910a3.png">

Google slides embed
Lines showing up on viewer

<img width="998" alt="Syntax vs  Style" src="https://user-images.githubusercontent.com/70187908/150567529-22070de7-4dd4-46a9-9c60-03e241c87d26.png">

Submitting Activity Error

<img width="893" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/70187908/150567614-dd3a5baa-71c8-4e98-a590-16711cc9d680.png">

￼

**Comment by briangormanly** [comment]
The error is fixed.
The issue with google slides was specific to safai and is actually due to google slides, not agora
