### ISSUE TITLE
Edit resource "expandable area" for less used fields

### ISSUE THREAD

**Issue by briangormanly** [briangormanly/agora#111]
Edit / modify resource pop-up on dashboard does not have the "expandable area" for the description, required and other less often used fields. An example of how this works can be seen on the goals edit screen also on the dashboard.

**Comment by briangormanly** [comment]
This issue might be outdated / depreciated by new UX design

**Comment by gutenberger** [comment]
UI Front end - Dilnaz Ramshi (PM Front End)

**Comment by briangormanly** [comment]
Part of old UI - On pause for now unless the new ui requires

**Comment by briangormanly** [comment]
Closing, this is old and will be re-evaluated as part of a future development cycle / launch
