### ISSUE TITLE
Research Web3 decentralization for user data

### ISSUE THREAD

**Issue by briangormanly** [briangormanly/agora#120]

**Comment by cmarcusdimarco** [comment]
@kiikoh @briangormanly would you two like to move to close out this issue, or would it be better to mark it as a future enhancement and update the project status to Backlog/On hold?

**Comment by briangormanly** [comment]
@kiikoh Go ahead and close this one as completed for now. If we take a second pass on something specific, we can open a new ticket.
@cmarcusdimarco
