### ISSUE TITLE
Bugfix Dashboard Edit does not work properly

### ISSUE THREAD

**Issue by KyleRessLiere** [briangormanly/agora#132]
Edit Resource just pull up Add Resource. Additionally authentication failed in terminal while this occurs. Shouldnt be able to add and access dash without authentication

![TerminalAuth](https://user-images.githubusercontent.com/55935877/190687133-28286738-2589-467e-aa7f-68aed5c29ea2.png)
![DashNotAuth](https://user-images.githubusercontent.com/55935877/190687134-70853bf8-b14b-407a-b51a-7a347be70c95.png)
![EditCreatePopUp](https://user-images.githubusercontent.com/55935877/190687136-478ae70e-22a8-4cbd-8446-5cc5e64541f2.png)

**Comment by briangormanly** [comment]
Completed
