### ISSUE TITLE
Due dates for PSRs need to re-evaluted for manager / leads

### ISSUE THREAD

**Issue by briangormanly** [briangormanly/agora#150]

**Comment by cmarcusdimarco** [comment]
For your reference, the structure my teams are (roughly) following is that engineers are submitting their PSRs to their respective senior engineer Saturday night/Sunday morning, and the senior engineers are sending me everything by 8 PM Sunday evening. I instructed the senior engineers to prepare their weekly recap/projection and SWOT analysis in advance and to address directly in their PSR if they did not receive one from a specific engineer in time.

I do think adding a buffer would help the senior engineers, but I think keeping Sunday as a deadline helps make sure teams are all on the same page by the time class starts Monday, and I think there is more value in the communication (or reporting the lack of communication up the chain).

What are your thoughts?

**Comment by briangormanly** [comment]
You make a good point. My initial concern was having enough time in the week to work before they have to submit it, for some the weekend is their best time to work.

I think the best way is to let each area handle it, as you have done. I will put together something formal to discuss with the class on Monday.

**Comment by briangormanly** [comment]
results are in the 9/26 class meeting notes

**Comment by briangormanly** [comment]
https://docs.google.com/document/d/1SVuhTIkERLmrxAuTnwiUlNxVZHRHW804KDJSD2MnkAs/edit#
