### ISSUE TITLE
Create Community Use Cases [Community Manager]

### ISSUE THREAD

**Issue by gutenberger** [briangormanly/agora#204]
Create Community Use case scenarios.
For example: Having a flagging mechanism for inappropriate resources posted.

**Comment by SurendraShrestha** [comment]
What could be the use case scenarios rather than flagging mechanism?
I went through the flagging mechanism and I had no idea about the other scenarios and what other sceniors cold be?

**Comment by gutenberger** [comment]
Another case could be a plagiarism flag for improper citation of research.

**Comment by gutenberger** [comment]
Just thought of another one: within the sharing mechanism, where do we focus our security efforts. Who is able to have access ect. Maybe we can work with the security team with that one.

**Comment by SurendraShrestha** [comment]
yeah that sounds dope. that will surely help in addition of use case. thank you

**Comment by briangormanly** [comment]
Incomplete, closing
