### ISSUE TITLE
Dynamically & Continuously Increment ids for all APIs (Keep Id the same on delete)

### ISSUE THREAD

**Issue by Mike-Volchko** [briangormanly/agora#227]

**Comment by cmarcusdimarco** [comment]
Per conversation with @Mike-Volchko - there was a concern regarding the previous name 'empty id on delete'. IDs should be single-use and not overwritten to avoid potential cases of GET requests intended for a previously deleted object returning a new, unintended object.

**Comment by TylerHernandez** [comment]
Please review the following document so I may know how to proceed. @cmarcusdimarco @Mike-Volchko @briangormanly 
https://docs.google.com/document/d/1x-IC8-5DHUyYss4VsvZ0bMt4UoDSQTLI4jWrR2ITL6k/edit?usp=sharing

**Comment by cmarcusdimarco** [comment]
@TylerHernandez I agree that the database should auto-increment and I think that would be the best case. That way we can do complete deletes of records and just return 404s if they're requested without having to do a second check on the data within.

**Comment by Mike-Volchko** [comment]
@TylerHernandez I agree with @cmarcusdimarco. Option one would be the best approach if it is possible. However, I think approach 4 is another possible path. What if we added a member that would signify that it has been deleted. This would also allow a user to undo a deletion if it was a mistake (almost like the trash function in docs/windows/etc.)

**Comment by cmarcusdimarco** [comment]
Placing issue on hold - need to confirm with @briangormanly how we want versioning to be implemented in the database. Should we be creating new entries in the database to preserve the older versions? If so, on what conditions and for how long?

**Comment by TylerHernandez** [comment]
Awaiting database team's changes -  "make goalId serial in data base(auto incrementing like other PKs), and return rId and goalId for inserts in the query and return only rId for update query"

**Comment by briangormanly** [comment]
Database cannot auto increment id as it is not the pk, it has to stay the same under the current design and be paired with a version to be unique. Service layer logic might require a new approach.
UUID might be best.

Ticket is staying open, needs to be addressed.

**Comment by briangormanly** [comment]
Using a UUID for the ID of workspaces instead of an id would solve this for workspaces. Going to try that path since I am doing db changes now anyway.

**Comment by briangormanly** [comment]
Unintentional close

**Comment by briangormanly** [comment]
Footnote for when this is revisited. I did not get as far as changing the integer rid to a uuid. It would probably be a good idea to change over resources and topic id's to uuids as well if undertaking this effort. It will likely have ramifications for the UI as the id is parsed in the client side JS to send back to the APIs.

**Comment by briangormanly** [comment]
Complete! WorkspaceId as well as topicId, resourceId, and userId have all been changed over to uuids.
