### ISSUE TITLE
Add a new way to update "position" field of shared DB table 'topic_resource' (Either by a new API route or an updated save method)

### ISSUE THREAD

**Issue by Mike-Volchko** [briangormanly/agora#232]

**Comment by Mike-Volchko** [comment]
Leaning towards updated save method.

**Comment by Caleb-Rogers** [comment]
Front-end needs this API to quickly move and change the order of the documents (Resources) vertically within a Topic via drag & drop. Hence, I believe a new API is needed.

**Comment by cmarcusdimarco** [comment]
@Caleb-Rogers check out line 552 of topicService.js - it looks like this feature is already implemented there by querying the topic table, using the fetched topic to query the topic_resource table, deleting the existing entry and creating a new entry in topic_resource with the updated resources, including their positions. This function is called within saveTopic() by the topicController on line 337.

Just needs resources to be passed through the request body.

**Comment by Mike-Volchko** [comment]
Reviewed with @Caleb-Rogers. It looks like this is already implemented as Marcus said above. We are going to keep the branch alive until the frontend confirms that this is functional. If it is functional, the branch will be deleted.
