### ISSUE TITLE
Create Unified Search API

### ISSUE THREAD

**Issue by kiikoh** [briangormanly/agora#235]
This will be capable of searching for users, resources, topics, workspaces, any more???

We will need to be conscious of how sharing is implemented so we can correctly search among public and shared items. In the first iteration of the search API it might make sense to only include users, and owned items.

Also, this is somewhat related to a stale issue #33, I felt it isn't quite the same thing.

**Comment by Christopher102** [comment]
So, just as a precursor I'm doing some reading while eating dinner.
https://www.coveo.com/blog/what-is-unified-search/
This article gives us a pretty good idea of what unified search would be like. For AGORAs needs, I'd imagine we'd want both our internal databases to show results, but also maybe we add an internet search component to it too at a later date?

**Comment by Christopher102** [comment]
A good example is something like the Windows Search Bar. If you type in something that the computer doesn't have, it'll prompt for you to search the web

**Comment by kiikoh** [comment]
Oh, ok, I see what you mean now... I see a use for that maybe more in suggestions pane? If it searched for scholarly articles you could use in your research, maybe automatically citing them or along those lines...
