### ISSUE TITLE
Update DB Script

### ISSUE THREAD

**Issue by Mike-Volchko** [briangormanly/agora#261]

**Comment by Mike-Volchko** [comment]
- Add Visibility

**Comment by Mike-Volchko** [comment]
Use original script and add:
- <entity name>_id
- Shared Table
- Goal -> Workspace

**Comment by cmarcusdimarco** [comment]
Goal to Workspace should take place in a fork of the existing repository, as it will require changes in the service layer as well. To avoid conflicts between dev environments, the current database should continue to use the goal terminology and a future team should refactor goal to workspace in a fork.
